<a href="https://colab.research.google.com/github/YS5-Red/Senior_Project/blob/main/Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working With Data

In [2]:

import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

training_data = datasets.FashionMNIST(
    root = "PyTorch",
    train = True,
    download = True,
    transform = ToTensor()
)

test_data = datasets.FashionMNIST(
    root = "PyTorch",
    train = False,
    download = True,
    transform = ToTensor()
)

batchsize = 64

#create Dataloaders
train_dataloader = DataLoader(training_data, batch_size = 64)
test_dataloader = DataLoader(test_data, batch_size = 64)

for X,y in test_dataloader:
    print(f"shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

  0%|          | 0/26421880 [00:00<?, ?it/s]

Extracting PyTorch/FashionMNIST/raw/train-images-idx3-ubyte.gz to PyTorch/FashionMNIST/raw



  0%|          | 0/29515 [00:00<?, ?it/s]

Extracting PyTorch/FashionMNIST/raw/train-labels-idx1-ubyte.gz to PyTorch/FashionMNIST/raw



  0%|          | 0/4422102 [00:00<?, ?it/s]

Extracting PyTorch/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to PyTorch/FashionMNIST/raw



  0%|          | 0/5148 [00:00<?, ?it/s]

Extracting PyTorch/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to PyTorch/FashionMNIST/raw

shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


# Creating Models

In [8]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

class NeuralNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28, 512),
        nn.ReLU(),
        nn.Linear(512, 512),
        nn.ReLU(),
        nn.Linear(512, 10)
    )
  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits

  model = NeuralNetwork().to(device)
  print(model)

Using cuda device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


# Tensors

In [16]:
import numpy as np

data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)
print(x_np)

# Ones and random tensor
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor \n {x_rand} \n")

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor 
 tensor([[0.3552, 0.9959],
        [0.0077, 0.2746]]) 

